import { PDFDocument, StandardFonts, rgb, grayscale, type PDFPage, type PDFFont } from "pdf-lib";
import type { ReportData } from "./report-types";

export type { ReportData };

export interface GeneratedReport {
  buffer: Uint8Array;
  filename: string;
}

// ─── Colour palette ───────────────────────────────────────────────────────────
const BRAND   = rgb(0.055, 0.455, 0.831); // #0E74D4
const DARK    = rgb(0.11,  0.11,  0.11);
const MUTED   = rgb(0.45,  0.45,  0.45);
const LIGHT   = rgb(0.96,  0.96,  0.97);
const WHITE   = rgb(1, 1, 1);
const SUCCESS = rgb(0.13, 0.65, 0.38);
const WARN    = rgb(0.93, 0.58, 0.11);
const DANGER  = rgb(0.86, 0.21, 0.27);

// ─── Page constants (A4 points) ───────────────────────────────────────────────
const PW = 595;   // page width
const PH = 842;   // page height
const ML = 50;    // margin left
const MR = 50;    // margin right
const CW = PW - ML - MR; // content width

// ─── Helpers ─────────────────────────────────────────────────────────────────

function fmt(n: number | null | undefined, prefix = "", suffix = "", decimals = 0): string {
  if (n == null) return "N/A";
  return `${prefix}${n.toLocaleString("en-AU", { maximumFractionDigits: decimals })}${suffix}`;
}

function pct(n: number | null | undefined): string {
  if (n == null) return "N/A";
  return `${(n * 100).toFixed(1)}%`;
}

function decileColour(d: number | null) {
  if (d == null) return MUTED;
  if (d >= 8) return SUCCESS;
  if (d >= 5) return WARN;
  return DANGER;
}

// Draw a filled rectangle
function rect(page: PDFPage, x: number, y: number, w: number, h: number, colour: ReturnType<typeof rgb>) {
  page.drawRectangle({ x, y, width: w, height: h, color: colour });
}

// Draw text with sensible defaults
function text(
  page: PDFPage,
  str: string,
  x: number,
  y: number,
  opts: { font: PDFFont; size: number; color?: ReturnType<typeof rgb>; maxWidth?: number }
) {
  page.drawText(str, { x, y, font: opts.font, size: opts.size, color: opts.color ?? DARK, maxWidth: opts.maxWidth });
}

// Draw a horizontal rule
function hr(page: PDFPage, y: number, color = LIGHT) {
  page.drawLine({ start: { x: ML, y }, end: { x: PW - MR, y }, thickness: 1, color });
}

// Draw a stat box: label on top, value below
function statBox(
  page: PDFPage,
  x: number, y: number, w: number,
  label: string, value: string,
  bold: PDFFont, regular: PDFFont
) {
  rect(page, x, y, w, 62, LIGHT);
  text(page, label, x + 10, y + 42, { font: regular, size: 8, color: MUTED });
  text(page, value, x + 10, y + 16, { font: bold, size: 16, color: DARK, maxWidth: w - 20 });
}

// Draw a section heading with accent bar
function sectionHeading(page: PDFPage, y: number, title: string, bold: PDFFont): number {
  rect(page, ML, y, 4, 18, BRAND);
  text(page, title, ML + 12, y + 4, { font: bold, size: 13, color: DARK });
  return y - 34;
}

// Draw a key/value row
function kvRow(page: PDFPage, y: number, label: string, value: string, regular: PDFFont, bold: PDFFont): number {
  text(page, label, ML, y, { font: regular, size: 9, color: MUTED });
  text(page, value, ML + 140, y, { font: bold, size: 9, color: DARK });
  return y - 16;
}

// ─── Page factory ─────────────────────────────────────────────────────────────

async function newPage(doc: PDFDocument, bold: PDFFont, regular: PDFFont, suburb: string): Promise<{ page: PDFPage; y: number }> {
  const page = doc.addPage([PW, PH]);

  // Header bar
  rect(page, 0, PH - 32, PW, 32, BRAND);
  text(page, "DemoReport", ML, PH - 22, { font: bold, size: 11, color: WHITE });
  text(page, suburb, PW - MR - 200, PH - 22, { font: regular, size: 9, color: WHITE, maxWidth: 200 });

  // Footer
  rect(page, 0, 0, PW, 24, LIGHT);
  text(page, "Generated by DemoReport · demoreport.com.au · ABS Census 2021 data", ML, 8, { font: regular, size: 7, color: MUTED });

  return { page, y: PH - 56 };
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Generate a DemoReport Feasibility Report PDF using pdf-lib.
 * Pure JS — no WASM, no Node.js APIs. Works in Cloudflare Workers.
 */
export async function generateFeasibilityReport(data: ReportData): Promise<GeneratedReport> {
  const doc = await PDFDocument.create();
  doc.setTitle(`DemoReport — ${data.suburb} ${data.state}`);
  doc.setAuthor("DemoReport");
  doc.setSubject(`Demographic Feasibility Report — ${data.suburb}, ${data.state}`);
  doc.setKeywords(["ABS", "Census", "SEIFA", "demographics", "feasibility"]);
  doc.setCreator("DemoReport (demoreport.com.au)");
  doc.setCreationDate(new Date());

  const bold    = await doc.embedFont(StandardFonts.HelveticaBold);
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const italic  = await doc.embedFont(StandardFonts.HelveticaOblique);

  const label = `${data.suburb}, ${data.state}${data.postcode ? ` ${data.postcode}` : ""}`;

  // ── Cover page ──────────────────────────────────────────────────────────────
  {
    const page = doc.addPage([PW, PH]);

    // Full-width brand header
    rect(page, 0, PH - 120, PW, 120, BRAND);
    text(page, "DemoReport", ML, PH - 55,  { font: bold, size: 28, color: WHITE });
    text(page, "Demographic Feasibility Report", ML, PH - 80, { font: regular, size: 14, color: rgb(0.75, 0.88, 0.97) });

    // Suburb badge
    rect(page, ML, PH - 175, CW, 44, LIGHT);
    text(page, label, ML + 14, PH - 146, { font: bold, size: 18, color: DARK });
    text(page, `SA2 Code: ${data.sa2Code}`, ML + 14, PH - 165, { font: regular, size: 9, color: MUTED });

    // Summary stat row
    const d = data.demographics;
    const h = data.housing;
    const boxW = (CW - 12) / 4;
    let bx = ML;
    const statY = PH - 265;

    const stats: [string, string][] = [
      ["Total Population",    fmt(d.totalPopulation)],
      ["Median Age",          fmt(d.medianAge, "", " yrs")],
      ["Median HH Income",    fmt(d.medianHouseholdIncome, "$", "/wk")],
      ["Median Rent",         fmt(h.medianRentWeekly, "$", "/wk")],
    ];
    for (const [lbl, val] of stats) {
      statBox(page, bx, statY, boxW, lbl, val, bold, regular);
      bx += boxW + 4;
    }

    // SEIFA highlight
    let sy = PH - 360;
    text(page, "SEIFA Indices (2021)", ML, sy, { font: bold, size: 12, color: DARK });
    sy -= 20;

    const indices: [string, number | null, number | null][] = [
      ["IRSD — Relative Socio-Economic Disadvantage", data.seifa.irsd, data.seifa.irsdDecile],
      ["IRSAD — Relative Socio-Economic Advantage & Disadvantage", data.seifa.irsad, data.seifa.irsadDecile],
      ["IER — Economic Resources", data.seifa.ier, data.seifa.ierDecile],
      ["IEO — Education & Occupation", data.seifa.ieo, data.seifa.ieoDecile],
    ];

    for (const [name, score, decile] of indices) {
      text(page, name, ML, sy, { font: regular, size: 9, color: MUTED, maxWidth: CW - 120 });
      text(page, fmt(score), ML + CW - 110, sy, { font: bold, size: 9, color: DARK });
      if (decile != null) {
        const col = decileColour(decile);
        rect(page, ML + CW - 60, sy - 2, 44, 14, col);
        text(page, `Decile ${decile}`, ML + CW - 57, sy + 1, { font: bold, size: 8, color: WHITE });
      }
      sy -= 20;
      hr(page, sy + 4, LIGHT);
    }

    // Disclaimer
    text(page, `Generated ${data.generatedAt} · Data: ABS Census 2021, SEIFA 2021`, ML, 60, { font: italic, size: 7.5, color: MUTED });
    text(page, "This report is provided for informational purposes only. Not financial or planning advice.", ML, 48, { font: italic, size: 7.5, color: MUTED });
  }

  // ── Page 2 — Demographics ──────────────────────────────────────────────────
  {
    const { page, y: startY } = await newPage(doc, bold, regular, label);
    let y = startY;

    y = sectionHeading(page, y, "Demographics", bold);

    const d = data.demographics;
    y = kvRow(page, y, "Total Population",           fmt(d.totalPopulation),                  regular, bold);
    y = kvRow(page, y, "Median Age",                 fmt(d.medianAge, "", " years"),           regular, bold);
    y = kvRow(page, y, "Median Household Income",    fmt(d.medianHouseholdIncome, "$", "/wk"), regular, bold);
    y = kvRow(page, y, "Median Personal Income",     fmt(d.medianPersonalIncome, "$", "/wk"),  regular, bold);
    y = kvRow(page, y, "Indigenous Population",      pct(d.indigenousPopulation),              regular, bold);
    y = kvRow(page, y, "Born Overseas",              pct(d.bornOverseas),                      regular, bold);
    y = kvRow(page, y, "Speaks English Only",        pct(d.speaksEnglishOnly),                 regular, bold);
    y -= 10;
    hr(page, y);
    y -= 20;

    // Age distribution bar chart
    y = sectionHeading(page, y, "Age Distribution", bold);
    const ad = d.ageDistribution;
    const bands: [string, number | null][] = [
      ["0–4",   ad["0_4"]],
      ["5–14",  ad["5_14"]],
      ["15–24", ad["15_24"]],
      ["25–34", ad["25_34"]],
      ["35–44", ad["35_44"]],
      ["45–54", ad["45_54"]],
      ["55–64", ad["55_64"]],
      ["65–74", ad["65_74"]],
      ["75+",   ad["75_plus"]],
    ];

    const barMaxW = CW - 100;
    const maxPct  = Math.max(...bands.map(([, v]) => v ?? 0));

    for (const [bandLabel, val] of bands) {
      const barW = maxPct > 0 && val != null ? (val / maxPct) * barMaxW : 0;
      text(page, bandLabel, ML, y + 2, { font: regular, size: 8, color: MUTED });
      rect(page, ML + 44, y, barW, 11, BRAND);
      text(page, pct(val), ML + 44 + barW + 6, y + 2, { font: regular, size: 8, color: MUTED });
      y -= 17;
    }
  }

  // ── Page 3 — Housing ───────────────────────────────────────────────────────
  {
    const { page, y: startY } = await newPage(doc, bold, regular, label);
    let y = startY;

    y = sectionHeading(page, y, "Housing", bold);

    const h = data.housing;
    y = kvRow(page, y, "Median Weekly Rent",     fmt(h.medianRentWeekly, "$", "/wk"),       regular, bold);
    y = kvRow(page, y, "Median Monthly Mortgage",fmt(h.medianMortgageMonthly, "$", "/mo"),   regular, bold);
    y = kvRow(page, y, "Median House Price",     fmt(h.medianHousePrice, "$"),               regular, bold);
    y = kvRow(page, y, "Total Dwellings",        fmt(h.totalDwellings),                      regular, bold);
    y = kvRow(page, y, "Owner-Occupied",         pct(h.ownerOccupied),                       regular, bold);
    y = kvRow(page, y, "Renting",                pct(h.renting),                             regular, bold);
    y = kvRow(page, y, "Social Housing",         pct(h.socialHousing),                       regular, bold);
    y -= 10;
    hr(page, y);
    y -= 20;

    // ── SEIFA detail ─────────────────────────────────────────────────────────
    y = sectionHeading(page, y, "SEIFA 2021 — Socio-Economic Indices", bold);

    const s = data.seifa;
    const rows: [string, number | null, number | null][] = [
      ["IRSD  Relative Disadvantage",             s.irsd,  s.irsdDecile],
      ["IRSAD Advantage & Disadvantage",          s.irsad, s.irsadDecile],
      ["IER   Economic Resources",                s.ier,   s.ierDecile],
      ["IEO   Education & Occupation",            s.ieo,   s.ieoDecile],
    ];

    for (const [name, score, decile] of rows) {
      text(page, name, ML, y, { font: regular, size: 9.5, color: DARK });
      text(page, `Score: ${fmt(score)}`, ML + CW - 160, y, { font: regular, size: 9, color: MUTED });
      if (decile != null) {
        const col = decileColour(decile);
        rect(page, ML + CW - 70, y - 2, 60, 15, col);
        text(page, `Decile ${decile}/10`, ML + CW - 67, y + 1, { font: bold, size: 8.5, color: WHITE });
      }
      y -= 22;
      hr(page, y + 6, LIGHT);
    }

    y -= 20;
    text(page, "Higher deciles indicate higher advantage. Decile 10 = most advantaged 10% of areas in Australia.", ML, y, { font: italic, size: 8, color: MUTED, maxWidth: CW });
    y -= 20;

    // ── Data sources ──────────────────────────────────────────────────────────
    y -= 10;
    hr(page, y);
    y -= 20;
    y = sectionHeading(page, y, "Data Sources", bold);
    const sources = [
      ["ABS Census 2021", "General Community Profile (GCP) — SA2 level"],
      ["SEIFA 2021",      "Socio-Economic Indexes for Areas — SA2 level"],
      ["Geography",       "ASGS Edition 3 — SA2/Postcode concordance"],
    ];
    for (const [src, detail] of sources) {
      text(page, `• ${src}`, ML, y, { font: bold, size: 8.5, color: DARK });
      text(page, detail, ML + 100, y, { font: regular, size: 8.5, color: MUTED, maxWidth: CW - 100 });
      y -= 16;
    }
  }

  const pdfBytes = await doc.save();
  const buffer   = new Uint8Array(pdfBytes);

  const slug = data.suburb
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

  const filename = `demoreport-${slug}-${data.state.toLowerCase()}-${data.censusYear}.pdf`;

  return { buffer, filename };
}

/**
 * Stub — Phase 3 will implement a multi-suburb comparison report.
 */
export async function generateNeedsAssessment(data: ReportData[]): Promise<GeneratedReport> {
  if (data.length === 0) throw new Error("generateNeedsAssessment: data array is empty");
  return generateFeasibilityReport(data[0]);
}
