import { StyleSheet } from "@react-pdf/renderer";

export const BRAND = {
  blue900: "#1e3a8a",
  blue700: "#1d4ed8",
  blue600: "#2563eb",
  blue400: "#60a5fa",
  blue100: "#dbeafe",
  blue50:  "#eff6ff",
  gray900: "#111827",
  gray700: "#374151",
  gray500: "#6b7280",
  gray300: "#d1d5db",
  gray100: "#f3f4f6",
  white:   "#ffffff",
};

export const base = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    color: BRAND.gray900,
    paddingTop: 40,
    paddingBottom: 52,
    paddingHorizontal: 48,
    backgroundColor: BRAND.white,
  },
  pageHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: BRAND.blue100,
    borderBottomStyle: "solid",
  },
  pageHeaderBrand: {
    fontSize: 8,
    color: BRAND.blue600,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 1,
  },
  pageHeaderRight: {
    fontSize: 8,
    color: BRAND.gray500,
  },
  pageFooter: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: BRAND.gray500,
    borderTopWidth: 1,
    borderTopColor: BRAND.gray300,
    borderTopStyle: "solid",
    paddingTop: 6,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: BRAND.blue900,
    marginBottom: 12,
  },
  sectionSubtitle: {
    fontSize: 9,
    color: BRAND.gray500,
    marginBottom: 16,
  },
  row: {
    flexDirection: "row",
    gap: 12,
  },
  statBox: {
    flex: 1,
    backgroundColor: BRAND.blue50,
    borderRadius: 6,
    padding: 10,
  },
  statLabel: {
    fontSize: 7,
    color: BRAND.blue700,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  statValue: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: BRAND.blue900,
  },
  statSub: {
    fontSize: 7,
    color: BRAND.gray500,
    marginTop: 2,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: BRAND.gray100,
    borderBottomStyle: "solid",
    paddingVertical: 5,
  },
  tableRowShaded: {
    backgroundColor: BRAND.gray100,
  },
  tableCell: {
    flex: 1,
    fontSize: 9,
    color: BRAND.gray700,
  },
  tableCellBold: {
    flex: 1,
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: BRAND.gray900,
  },
  barContainer: {
    marginBottom: 6,
  },
  barLabel: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  barLabelText: {
    fontSize: 8,
    color: BRAND.gray700,
  },
  barTrack: {
    height: 8,
    backgroundColor: BRAND.gray100,
    borderRadius: 4,
  },
  barFill: {
    height: 8,
    backgroundColor: BRAND.blue600,
    borderRadius: 4,
  },
  infoBox: {
    backgroundColor: BRAND.blue50,
    borderLeftWidth: 3,
    borderLeftColor: BRAND.blue600,
    borderLeftStyle: "solid",
    padding: 10,
    marginBottom: 12,
    borderRadius: 4,
  },
  infoBoxText: {
    fontSize: 9,
    color: BRAND.blue900,
    lineHeight: 1.5,
  },
  caveat: {
    fontSize: 7.5,
    color: BRAND.gray500,
    marginTop: 8,
    lineHeight: 1.4,
  },
});
